# Generated by Django 6.1 on 2026-08-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptionjob',
            name='segments_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
