# Generated by Django 6.1 on 2026-08-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0002_transcriptionjob_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='partial_segments_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
