# Generated by Django 6.1 on 2026-08-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0003_transcriptionjob_partial_segments_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptionjob',
            name='partial_segments_json',
        ),
    ]
