# Generated by Django 6.1 on 2026-08-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0004_remove_transcriptionjob_partial_segments_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='model_name',
            field=models.CharField(default='small', max_length=20),
        ),
    ]
